name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install pytest pytest-cov coverage; fi

    # pytest.ini in your repo already has coverage addopts, so a plain pytest is fine.
    - name: Run tests
      run: |
        pytest

    # Enforce 100% coverage (fail build if below 100)
    - name: Enforce coverage threshold
      run: |
        coverage report --fail-under=100
